name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5  # add dependency for Firebase Core
  firebase_auth: ^0.14.0+5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets: [Images/RipulAgrawal.jpg]
  fonts:
     - family: Pacifico
       fonts:
         - asset: fonts/Pacifico-Regular.ttf
     - family: Source Sans Pro
       fonts:
         - asset: fonts/SourceSansPro-Regular.ttf



